cd

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -3,47 +3,41 @@ name: CD
 on:
   push:
     branches:
-      - main # 'main' branchga push qilganda trigger bo'ladi
+      - main
 
 jobs:
   deploy:
     runs-on: ubuntu-latest
 
     steps:
-      # Step 1: Checkout the code
       - name: Checkout code
         uses: actions/checkout@v2
 
-      # Step 2: Set up Node.js v22
-      - name: Set up Node.js v22
-        uses: actions/setup-node@v3
+      - name: Setup Node.js
+        uses: actions/setup-node@v2
         with:
-          node-version: '22' # Node.js versiyasini 22 ga o'rnatish
+          node-version: '20' # Node versiyasi
 
-      # Step 3: Install npm, pm2 globally
-      - name: Install npm and pm2 globally
-        run: |
-          sudo apt-get update
-          sudo apt-get install -y npm
-          sudo npm install -g pm2  # PM2 ni global tarzda o'rnatish
+      - name: Install dependencies
+        run: npm install
 
-      # Step 4: SSH through to the server and pull the latest changes
-      - name: SSH and pull the latest changes
+      - name: Setup SSH
         uses: appleboy/ssh-action@master
+        id: ssh
         with:
           host: ${{ secrets.HOST_NAME }}
           username: ${{ secrets.USERNAME }}
           key: ${{ secrets.SSH_PRIVATE_KEY }}
           port: 22
           script: |
-            cd ~/arendumAPI  # Loyiha papkasiga o'tish
-            git pull origin main  # Git repozitoriyasidan so'nggi o'zgarishlarni olish
-            npm install  # Barcha kerakli paketlarni o'rnatish
-            npx prisma migrate deploy  # Prisma migratsiyasini bajarish
-            npx prisma generate  # Prisma fayllarini generatsiya qilish
-            pm2 restart 0  # PM2 orqali ilovani qayta ishga tushirish
+            cd ~/ecommApi/
+            git stash || { echo "git stash failed"; exit 1; }
+            git pull origin main || { echo "git pull failed"; exit 1; }
+            npm install
+            npx prisma migrate deploy || { echo "prisma migrate deploy failed"; exit 1; }
+            npx prisma generate || { echo "prisma generate failed"; exit 1; }
+            pm2 restart 0 || { echo "pm2 restart failed"; exit 1; }
 
-      # Step 5: Notify Telegram on success
       - name: Notify Telegram on success
         if: success()
         run: |
@@ -51,9 +45,8 @@ jobs:
           COMMIT_AUTHOR=$(git log -1 --pretty=format:"%an")
           curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
           -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
-          -d text="CD Successfully.%0ACommit: $COMMIT_MESSAGE%0AAuthor: $COMMIT_AUTHOR"
+          -d text="CD Successfully.\\nCommit: $COMMIT_MESSAGE\\nAuthor: $COMMIT_AUTHOR"
 
-      # Step 6: Notify Telegram on failure
       - name: Notify Telegram on failure
         if: failure()
         run: |
