cool

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -10,39 +10,34 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      # Step 1: Checkout code
       - name: Checkout code
         uses: actions/checkout@v2
 
-      # Step 2: Set up Node.js v22
-      - name: Set up Node.js 22
-        uses: actions/setup-node@v3
+      - name: Setup Node.js
+        uses: actions/setup-node@v2
         with:
-          node-version: '22' # Set Node.js version to 22
-          cache: 'pnpm' # Cache pnpm packages
+          node-version: '22' # Node versiyasi
 
-      # Step 3: Install pnpm globally
-      - name: Install pnpm
-        run: |
-          npm install -g pnpm  # Install pnpm globally
+      - name: Install dependencies
+        run: pnpm install
 
-      # Step 4: Setup SSH and run necessary commands
-      - name: Setup SSH and deploy
+      - name: Setup SSH
         uses: appleboy/ssh-action@master
+        id: ssh
         with:
-          host: ${{ secrets.HOST }}
+          host: ${{ secrets.HOST_NAME }}
           username: ${{ secrets.USERNAME }}
-          key: ${{ secrets.SSH_PRIVATE_KEY }}
+          key: ${{ secrets.SSH_PRIVATE_KEY  }}
           port: 22
           script: |
-            # Node.js versiyasini tekshirish
-            node -v
+            cd ~/arendum-api/
+            git stash || { echo "git stash failed"; exit 1; }
+            git pull origin main || { echo "git pull failed"; exit 1; }
             pnpm install
-            npx prisma migrate deploy --name migrated  # Prisma migratsiya
-            npx prisma generate  # Prisma fayllarini generatsiya qilish
+            npx prisma generate
+            npx prisma migrate deploy
             pm2 restart 0
 
-      # Step 5: Notify Telegram on success
       - name: Notify Telegram on success
         if: success()
         run: |
@@ -50,9 +45,8 @@ jobs:
           COMMIT_AUTHOR=$(git log -1 --pretty=format:"%an")
           curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
           -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
-          -d text="CD Successfully.%0ACommit: $COMMIT_MESSAGE%0AAuthor: $COMMIT_AUTHOR"
+          -d text="CD Successfully.\\nCommit: $COMMIT_MESSAGE\\nAuthor: $COMMIT_AUTHOR"
 
-      # Step 6: Notify Telegram on failure
       - name: Notify Telegram on failure
         if: failure()
         run: |
